trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    exclude:
      - "*"
pr:
  autoCancel: true
  branches:
    include:
      - master

variables:
  - group: codecov
  - name: poetry_home
    value: $( format('{0}/.poetry', variables['Pipeline.Workspace']) )

stages:
  - template: stage-lint.yml
  - template: stage-test.yml
    parameters:
      pythonVersions:
        - "3.6"
        - "3.7"
        - "3.8"
